parameters:
  - name: environment
    type: string
  



# jobs:
# - job:
#   steps:
#   - task: HelmDeploy@1
#     inputs:
#       connectionType: 'Kubernetes Service Connection'
#       kubernetesServiceConnection: 'k8'
#       azureSubscriptionForACR: 'Free Trial(89449e9c-294c-4edc-9bb8-c5168253b160)'
#       azureResourceGroupForACR: 'Containers_RG'
#       azureContainerRegistry: 'uservice.azurecr.io'
#       namespace: 'default'
#       command: 'upgrade'
#       chartType: 'Name'
#       chartName: 'oci://uservice.azurecr.io/helm/uservice'
#       chartVersion: '0.1.0'
#       releaseName: 'nginx'
#       overrideValues: 'image.tag=latest'



steps:
- task: bash@3
  displayName: 'Test ${{ parameters.environment }} Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo "Testing ${{ parameters.environment }} Deployment" 
