
parameters:
  - name: tag
    type: string
    default: '$(Build.BuildId)'

jobs:
- job: BuildAndScan
  displayName: Docker build
  pool:
    name: default 
  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: uservice
      command: build
      dockerfile: '$(Build.SourcesDirectory)/dockerfile'
      tags: |
        $(tag)
  - task: CmdLine@2
    displayName: Clean docker resources
    inputs:
      script: 'docker system prune -a --force' 
