parameters:
  - name: serviceConnectionEndpoint
    type: string
    default: 'Snyk_Analysis'
  - name: testType
    type: string
    default: 'code'
  - name: codeSeverityThreshold
    type: string
    default: 'high'
  - name: failOnIssues
    type: boolean
    default: true
  - name: projectName
    type: string
    default: '$(Build.Repository.Name)'
  - name: organization
    type: string
    default: 'rjt.rjtshrm94'


jobs:
- job: SnykSecurityScanCode
  displayName: Snyk Security Scan Code
  steps:
  - task: SnykSecurityScan@1
    displayName: Code Analysis
    inputs:
      serviceConnectionEndpoint: ${{ parameters.serviceConnectionEndpoint }}
      testType: ${{ parameters.testType }}
      codeSeverityThreshold: ${{ parameters.codeSeverityThreshold }}
      failOnIssues: ${{ parameters.failOnIssues }}
      projectName: ${{ parameters.projectName }}
      organization: ${{ parameters.organization }}